POST {{base_url}}/users/login/
Content-Type: application/json

{
    "username": "{{login}}",
    "password": "{{password}}"
}

###

GET {{base_url}}/cards/
Accept: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyMzksInVzZXJuYW1lIjoiYXJtYWRhIiwiZXhwIjoxNjA3ODkwNjE1LCJlbWFpbCI6IiIsIm9yaWdfaWF0IjoxNjA3ODg3MDE1fQ.jtKS9RoRku_BQF6NvLDMaCDISy1RagGDZ-peINYH20o


###

POST {{base_url}}/users/login/
Content-Type: application/json

{
    "username": "{{login}}",
    "password": "{{password}}"
}




